#ifndef EMU_MATH_QUATERNION_UNDERLYING_CONVERSIONS_H_INC_
#define EMU_MATH_QUATERNION_UNDERLYING_CONVERSIONS_H_INC_ 1

#include "_conversions/_quaternion_underlying_conversion_from_euler.h"
#include "_conversions/_quaternion_underlying_conversion_to_euler.h"

#endif
